routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{

	Route::get('/', 'Index@home');

	Route::get('/home', 'Index@index')->name('home');

	Route::get('/gallery', 'Gallery@index')->name('gallery');

	Route::get('/products', 'Products@index')->name('products');

	Route::get('/career', 'Career@index')->name('career');

	Route::resource('index', 'Index');

	Route::resource('career', 'Career',['except' => ['index']]);

});

Auth::routes();

//ADMIN
Route::group(['prefix' => 'administrator'], function()
{
	Route::get('/', 'Admin@index')->name('admin');

	Route::get('/logout', 'Admin@logout')->name('logout');

	Route::get('/translations', 'Admin@translations')->name('translations');

	Route::get('/forms', 'Admin@forms')->name('forms');

	Route::get('/getForms', array('uses' => 'Admin@getForms'))->name('getForms');

	Route::resource('/clients', 'AdminClients',['except' => ['show']]);
	Route::get('/getServices', array('uses' => 'AdminClients@getServices'))->name('getServices');

	Route::resource('/gallery', 'AdminGallery',['except' => ['show']]);
	Route::get('/getGallery', array('uses' => 'AdminGallery@getGallery'))->name('getGallery');

	Route::resource('/gallery/category', 'AdminGalleryCategory',['except' => ['show', 'create', 'store']]);
	Route::get('/getGalleryCategory', array('uses' => 'AdminGalleryCategory@getGalleryCategory'))->name('getGalleryCategory');
});

resources/views/admin/clients/create.blade.php
@extends('admin.layout.app')
@section('title')
Create Clients
@endsection

@section('content')
<div class="grid-form1">
      @if($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    
 		<h2 id="forms-example" class="">Create Clients</h2>

{{ Form::open(['route' => 'clients.store']) }}
<div class="form-group">
    {!! Form::label('Name', 'Name', ['class' => 'control-label']) !!}
    {!! Form::text('Name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'ShortDesc', ['class' => 'control-label']) !!}
    {!! Form::text('ShortDesc', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Description', ['class' => 'control-label']) !!}
    {!! Form::textarea('Description', null, ['class' => 'form-control']) !!}
</div>

  {{Form::submit('Submit',['class'=>'btn btn-default form-control'])}}
{{ Form::close() }}

</div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layout.app')
@section('title')
Edit Clients
@endsection

@section('content')
<div class="grid-form1">
    @if($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    
 		<h2 id="forms-example" class="">Edit Clients</h2>

{{ Form::model($data, [
    'method' => 'PATCH',
    'route' => ['clients.update', $data->ServicesId]
]) }}

<div class="form-group">
    {!! Form::label('Name', 'Name', ['class' => 'control-label']) !!}
    {!! Form::text('Name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'ShortDesc', ['class' => 'control-label']) !!}
    {!! Form::text('ShortDesc', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Description', ['class' => 'control-label']) !!}
    {!! Form::textarea('Description', null, ['class' => 'form-control']) !!}
</div>

  {{Form::submit('Submit',['class'=>'btn btn-default form-control'])}}
{{ Form::close() }}

</div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layout.app')


@section('title')
Clients
@endsection

@section('content')
@if(Session::has('message'))
  <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
@endif
<div class="bs-component mb20" style="float:right; width: 20%">
   <a href="{{route('clients.create')}}"><button type="button" class="btn btn-primary btn-block">Create</button></a>
</div>
<table id="table" class="table table-striped table-bordered" width="100%" cellspacing="0">
<thead>
	<tr>
	  <th>ID</th>
		<th>Name</th>
		<th>Short Description</th>
    <th>Description</th>
    <th class="Edit"></th>
    <th class="Delete"></th>
	</tr>
</thead>
</table>
@endsection


@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    $('#table').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "{{route('getServices')}}",
        "order": [[ 0, "desc" ]],
        "columns": [
            { data: 'ServicesId', name: 'ID' },
            { data: 'Name', name: 'Name' },
            { data: 'ShortDesc', name: 'Short Description' },
            { data: 'Description', name: 'Description'},
            { data: 'edit', name: 'Edit'},
            { data: 'delete', name: 'Delete'}
        ]
    } );
} );
</script>

<script>
      function ConfirmDelete()
      {
      var x = confirm("Are you sure you want to delete?");
      if (x)
        return true;
      else
        return false;
      }
</script>
@endpush