routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{

	Route::get('/', 'Index@home');

	Route::get('/home', 'Index@index')->name('home');

	Route::get('/gallery', 'Gallery@index')->name('gallery');

	Route::get('/products', 'Products@index')->name('products');

	Route::get('/career', 'Career@index')->name('career');

	Route::resource('index', 'Index');

	Route::resource('career', 'Career',['except' => ['index']]);

});

Auth::routes();

//ADMIN
Route::group(['prefix' => 'administrator'], function()
{
	Route::get('/', 'Admin@index')->name('admin');

	Route::get('/logout', 'Admin@logout')->name('logout');

	Route::get('/translations', 'Admin@translations')->name('translations');

	Route::get('/forms', 'Admin@forms')->name('forms');

	Route::get('/getForms', array('uses' => 'Admin@getForms'))->name('getForms');

	Route::resource('/clients', 'AdminClients',['except' => ['show']]);
	Route::get('/getServices', array('uses' => 'AdminClients@getServices'))->name('getServices');

	Route::resource('/gallery', 'AdminGallery',['except' => ['show']]);
	Route::get('/getGallery', array('uses' => 'AdminGallery@getGallery'))->name('getGallery');

	Route::resource('/gallery/category', 'AdminGalleryCategory',['except' => ['show', 'create', 'store']]);
	Route::get('/getGalleryCategory', array('uses' => 'AdminGalleryCategory@getGalleryCategory'))->name('getGalleryCategory');
});

app/Http/Controllers/Gallery.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\TblAAMProducts;
use App\TblAAMProductsCategory;

class Gallery extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=array();
        $data['products'] = TblAAMProducts::get();
        $data['categories'] = TblAAMProductsCategory::get();
        return view('gallery.index')->with($data);
    }

}

resources/views/admin/gallery/create.blade.php
@extends('admin.layout.app')
@section('title')
Create Gallery
@endsection

@section('content')
<div class="grid-form1">
      @if($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    
 		<h2 id="forms-example" class="">Create Gallery</h2>

{{ Form::open(['route' => 'gallery.store', 'files' => true]) }}
 <div class="form-group">
    {!! Form::label('title', 'Name', ['class' => 'control-label']) !!}
    {!! Form::text('MediaName', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Image (JPG, PNG)', ['class' => 'control-label']) !!}
    {!! Form::file('FileName') !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Category', ['class' => 'control-label']) !!}
    <select name="ProductsCategoryId" class="form-control" onchange="CheckColors(this.value)";>
    <option value="" disabled selected>--Choose Category--</option>
    <option value="New">New Category</option>
    @foreach ($categories as $category)
      <option value="{{$category->ProductsCategoryId}}">{{$category->CategoryName}}</option>
    @endforeach
    </select>
</div>
<div class="form-group" id="NewCategory" style="display:none;">
    {!! Form::label('title', 'New Category Name', ['class' => 'control-label']) !!}
    {!! Form::text('NewCategoryName', null, ['class' => 'form-control']) !!}
</div>
  {{Form::submit('Submit',['class'=>'btn btn-default form-control'])}}
{{ Form::close() }}

</div>
@endsection

@push('scripts')
<script type="text/javascript">
function CheckColors(val){
 var element=document.getElementById('NewCategory');
 if(val=='New')
   element.style.display='block';
 else  
   element.style.display='none';
}
</script> 
@endpush

resources/views/admin/gallery/edit.blade.php
@extends('admin.layout.app')
@section('title')
Edit Gallery
@endsection

@section('content')
<div class="grid-form1">
    @if($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    
 		<h2 id="forms-example" class="">Edit Gallery</h2>

{{ Form::model($data, [
    'method' => 'PATCH',
    'route' => ['gallery.update', $data->ProductsId],
    'files' => true
]) }}
<div class="form-group">
    {!! Form::label('title', 'Name', ['class' => 'control-label']) !!}
    {!! Form::text('MediaName', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Image (JPG, PNG)', ['class' => 'control-label']) !!}
    {!! Form::file('FileName') !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Category', ['class' => 'control-label']) !!}
    <select name="ProductsCategoryId" class="form-control" onchange="CheckColors(this.value)";>
    <option value="" disabled>--Choose Category--</option>
    <option value="New">New Category</option>
    @foreach ($categories as $category)
      <option value="{{$category->ProductsCategoryId}}"
      @if ($data->ProductsCategoryId == $category->ProductsCategoryId)
      {{'selected'}}
      @endif
      >{{$category->CategoryName}}</option>
    @endforeach
    </select>
</div>
<div class="form-group" id="NewCategory" style="display:none;">
    {!! Form::label('title', 'New Category Name', ['class' => 'control-label']) !!}
    {!! Form::text('NewCategoryName', null, ['class' => 'form-control']) !!}
</div>
  {{Form::submit('Submit',['class'=>'btn btn-default form-control'])}}
{{ Form::close() }}

</div>
@endsection


@push('scripts')
<script type="text/javascript">
function CheckColors(val){
 var element=document.getElementById('NewCategory');
 if(val=='New')
   element.style.display='block';
 else  
   element.style.display='none';
}
</script> 
@endpush

resources/views/admin/gallery/index.blade.php
@extends('admin.layout.app')


@section('title')
Gallery
@endsection

@section('content')
@if(Session::has('message'))
  <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
@endif
<div class="bs-component mb20" style="float:right; width: 20%">
   <a href="{{route('gallery.create')}}"><button type="button" class="btn btn-primary btn-block">Create</button></a>
</div>
<div class="bs-component mb20" style="float:left; width: 20%">
      <a href="{{route('category.index')}}"><button type="button" class="btn btn-primary btn-block">Go to Categories</button></a>
</div>
<table id="table" class="table table-striped table-bordered" width="100%" cellspacing="0">
<thead>
	<tr>
	  <th>ID</th>
		<th>Name</th>
		<th>File Name</th>
    <th>Category</th>
    <th class="Edit"></th>
    <th class="Delete"></th>
	</tr>
</thead>
</table>
@endsection


@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    $('#table').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "{{route('getGallery')}}",
        "order": [[ 0, "desc" ]],
        "columns": [
            { data: 'ProductsId', name: 'ID' },
            { data: 'MediaName', name: 'Name' },
            { data: 'FileName', name: 'File Name' },
            { data: 'category.CategoryName', name: 'Category'},
            { data: 'edit', name: 'Edit'},
            { data: 'delete', name: 'Delete'}
        ],
      "columnDefs": [
      {
        data: 'FileName',
        searchable: false,
        "render": function(data, type, row) { // Available data available for you within the row
        return "<a href='{{asset('/images/gallery')}}/"+data+"' target='_blank'>"+data+"</a>";
        },
        "targets" : 2
      }
      ]
    } );
} );
</script>

<script>
      function ConfirmDelete()
      {
      var x = confirm("Are you sure you want to delete?");
      if (x)
        return true;
      else
        return false;
      }
</script>
@endpush